server:
  port: 8080
  servlet:
    context-path: /api/

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/hamster_db?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:1329623049}
    initialization-mode: always
    schema: classpath:schema.sql
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:1329623049}
  tomcat:
    max-http-form-post-size: 200MB
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true

sms:
  ali:
    accessKeyId: ${ACCESS_KEY_ID}
    accessKeySecret: ${ACCESS_KEY_SECRET}
    sysRegionId: ${SYS_REGION_ID}
    signName: ${SIGN_NAME}
    templateCode: ${TEMPLATE_CODE}
  tencent:
    secretId: ${SECRET_ID}
    secretKey: ${SECRET_KEY}
    region: ${REGION}
    sdkAppId: ${SDK_APP_ID}
    signName: ${SIGN_NAME}
    templateId: ${TEMPLATE_ID}

bit-torrent:
  address: ${BIT_ADDRESS:http://localhost}:${BIT_PORT:8888}
  username: ${BIT_USERNAME:admin}
  password: ${BIT_PASSWORD:admin132}

  producer:
    group: producer-hh
  consumer:
    group: consumer-hh