version: '3'
services:
  api:
    image: kougami132/hamsterhub-api
    container_name: hh-api
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./uploads:/app/uploads
      - ./avatars:/app/avatars
      - ./temp:/app/temp
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=<PASSWORD> # 自行修改密码
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=<PASSWORD> # 自行修改密码
      - SECRET_ID=<SECRET_ID>
      - SECRET_KEY=<SECRET_KEY>
      - REGION=ap-guangzhou
      - SDK_APP_ID=1400904738
      - SIGN_NAME=kougamiCn网
      - TEMPLATE_ID=2134000
      - BIT_ADDRESS=qb
      - BIT_PORT=8888
      - BIT_USERNAME=admin
      - BIT_PASSWORD=adminadmin
    depends_on:
      - mysql
      - redis
      - qb

  mysql:
    image: mysql:8.0.33
    container_name: hh-mysql
    restart: unless-stopped
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<PASSWORD> # 需和上面的MYSQL_PASSWORD一致
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
      - TZ=Asia/Shanghai

  redis:
    image: redis:6.0
    container_name: hh-redis
    restart: unless-stopped
    expose:
      - '6379'
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/logs
    command:
      redis-server /usr/local/etc/redis/redis.conf --requirepass <PASSWORD> # 需和上面的REDIS_PASSWORD一致

  qb:
    image: linuxserver/qbittorrent
    container_name: hh-qb
    restart: unless-stopped
    expose:
      - '8888'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
      - WEBUI_PORT=8888 # 将此处修改成你欲使用的 WEB 管理平台端口
    volumes:
      - ./qb-config:/config # 绝对路径请修改为自己的config文件夹
      - ./temp:/downloads # 绝对路径请修改为自己的downloads文件夹

networks:
  default:
    name: network_hh